import type { AppLocale } from "@/lib/locale";

const en = {
  navHome: "Home",
  navProjects: "Projects",
  navCommunity: "Community",
  navOperator: "User",
  mainNavigation: "Navigation",
  navProjectsSubtitle: "Track project progress and needs.",
  navCommunitySubtitle: "Which items does my community need?",
  navOperatorSubtitle: "Configuration, expeditions, device management",
  projectSelection: "Project selection",
  scanning: "Scanning...",
  synced: "Signed in",
  scanningProjectCache: "Scanning project cache...",
  scanningExpeditionIndex: "Scanning expedition index...",
  activeProject: "Active",
  noSignalPendingQueue: "No signal. Project data not found.",
  archived: "Archived",
  noArchivedSignal: "No projects completed.",
  back: "Back",
  quicksearch: "Quicksearch",
  searchPlaceholder: "SEARCH...",
  filterNeededOnly: "Show needed items only",
  neededOnly: "Needed only",
  noSignalProjectData: "No signal. Project data not found.",
  show: "Show",
  hide: "Hide",
  dataNotFoundScanning: "Data not found. Scanning...",
  noSignalDataNotFound: "No signal. Data not found.",
  noSignalExpeditionData: "No signal. Expedition data not found.",
  noSignalRaiderNotLinked: "No signal. User not signed in.",
  raiderLabel: "User",
  authCodeLabel: "Login Code",
  authCodeValueAria: "Login code",
  authCodeHint: "Use this code on another device to sign in.",
  copy: "Copy",
  copied: "Copied",
  edit: "Edit",
  activeExpeditionLabel: "Active Expedition",
  noExpedition: "NO EXPEDITION",
  unknownExpedition: "UNKNOWN EXPEDITION",
  expeditionReady: "READY",
  updateFailed: "Update failed",
  logOut: "Log Out",
  authRegister: "Register",
  authUseCode: "Use Code",
  onboardingAccountPrompt: "Do you already have an account?",
  onboardingAccountHelp: "Choose how to link your user.",
  onboardingExistingHelp:
    "Generate an auth code on your existing device (User menu) and enter it below.",
  onboardingNewIntroTitle: "Welcome to Raiders Outpost",
  onboardingNewIntroBody:
    "Track what you need in Arc Raiders for workbenches, projects, and expeditions.",
  onboardingProjectsTitle: "Workbenches & Projects",
  onboardingProjectsBody:
    "Workbenches & projects are your core progression. Mark what you've already completed.",
  onboardingExpeditionsTitle: "Expeditions",
  onboardingExpeditionsBody:
    "Expeditions are optional. How many have you already completed?",
  onboardingNoExpeditions: "No expeditions",
  onboardingExpeditionsDone: "Expeditions completed",
  onboardingBack: "Back",
  onboardingNext: "Next",
  raiderNameLabel: "User Name",
  callsignPlaceholder: "Enter user name",
  progressBaseline: "Progress baseline",
  selectCompletedProjects: "Select completed projects",
  completeLabel: "Complete",
  stageComplete: "Stage complete",
  expeditionControl: "Expedition control",
  selectActiveExpedition: "Select active expedition",
  authCodePlaceholder: "ENTER LOGIN CODE",
  authCodeValid: "Login code valid for 5 minutes",
  syncUplink: "Register",
  nameRequired: "Name required",
  authFailed: "Auth failed",
  codeRequired: "Code required",
  codeExpired: "Code expired",
  codeInvalid: "Code invalid",
  syncingUplink: "Checking link...",
  noRaiderLinked: "No user signed in.",
  communityLabel: "Community",
  rosterTitle: "Members",
  noSignal: "No signal.",
  establishUplink: "Create a community to get started.",
  joiningUplink: "Joining community...",
  communityNameLabel: "Community Name",
  communityNamePlaceholder: "Enter community name",
  createCommunity: "Create community",
  needsVerb: "needs",
  membersLabel: "Members",
  severUplink: "Remove User",
  inviteLinkTitle: "Invite link",
  inviteLinkAria: "Invite link",
  inviteHelp: "Share the link to add more users.",
  confirmRemoval: "Confirm removal",
  actionLabel: "Action",
  removeRaiderPrompt: "Remove user from crew?",
  cancel: "Cancel",
  confirm: "Confirm",
  severing: "Removing...",
  raiders: "Users",
  closeOverlay: "Close overlay",
  close: "Close",
  unknownLabel: "Unknown",
  increase: "Increase",
  decrease: "Decrease",
  of: "of",
  noSignalTitle: "No Signal",
  idLabel: "ID",
} as const;

type Labels = Record<keyof typeof en, string>;

const de: Labels = {
  navHome: "Home",
  navProjects: "Projekte",
  navCommunity: "Community",
  navOperator: "User",
  mainNavigation: "Navigation",
  navProjectsSubtitle: "Projektfortschritt und Bedarf verfolgen.",
  navCommunitySubtitle: "Welche Items braucht meine Community?",
  navOperatorSubtitle: "Konfiguration, Expedition, Geräteverwaltung",
  projectSelection: "Projektauswahl",
  scanning: "Scanne...",
  synced: "Angemeldet",
  scanningProjectCache: "Scanne Projekt-Cache...",
  scanningExpeditionIndex: "Scanne Expeditionsindex...",
  activeProject: "Aktiv",
  noSignalPendingQueue: "Kein Signal. Projektdaten nicht gefunden.",
  archived: "Archiviert",
  noArchivedSignal: "Keine Projekte abgeschlossen.",
  back: "Zurück",
  quicksearch: "Schnellsuche",
  searchPlaceholder: "SUCHE...",
  filterNeededOnly: "Nur benötigte Items anzeigen",
  neededOnly: "Nur benötigt",
  noSignalProjectData: "Kein Signal. Projektdaten nicht gefunden.",
  show: "Anzeigen",
  hide: "Ausblenden",
  dataNotFoundScanning: "Daten nicht gefunden. Scanne...",
  noSignalDataNotFound: "Kein Signal. Daten nicht gefunden.",
  noSignalExpeditionData: "Kein Signal. Expeditionsdaten nicht gefunden.",
  noSignalRaiderNotLinked: "Kein Signal. User nicht angemeldet.",
  raiderLabel: "User",
  authCodeLabel: "Login-Code",
  authCodeValueAria: "Login-Code",
  authCodeHint: "Nutze diesen Code auf einem anderen Gerät, um dich anzumelden.",
  copy: "Kopieren",
  copied: "Kopiert",
  edit: "Bearbeiten",
  activeExpeditionLabel: "Aktive Expedition",
  noExpedition: "KEINE EXPEDITION",
  unknownExpedition: "UNBEKANNTE EXPEDITION",
  expeditionReady: "BEREIT",
  updateFailed: "Update fehlgeschlagen",
  logOut: "Abmelden",
  authRegister: "Registrieren",
  authUseCode: "Code verwenden",
  onboardingAccountPrompt: "Hast du bereits einen Account?",
  onboardingAccountHelp: "Wähle den Weg zum Verknüpfen deines Users.",
  onboardingExistingHelp:
    "Erzeuge einen Auth-Code auf deinem bestehenden Gerät (User-Menü) und gib ihn unten ein.",
  onboardingNewIntroTitle: "Willkommen bei Raiders Outpost",
  onboardingNewIntroBody:
    "Verfolge, was du in Arc-Raiders für Werkbänke, Projekte und Expeditionen brauchst.",
  onboardingProjectsTitle: "Werkbänke & Projekte",
  onboardingProjectsBody:
    "Werkbänke & Projekte sind dein Kernfortschritt. Markiere, was du bereits abgeschlossen hast.",
  onboardingExpeditionsTitle: "Expeditionen",
  onboardingExpeditionsBody:
    "Expeditionen sind optional. Wie viele hast du bereits abgeschlossen?",
  onboardingNoExpeditions: "Keine Expeditionen",
  onboardingExpeditionsDone: "Expeditionen erledigt",
  onboardingBack: "Zurück",
  onboardingNext: "Weiter",
  raiderNameLabel: "User-Name",
  callsignPlaceholder: "User-Name eingeben",
  progressBaseline: "Fortschritts-Basis",
  selectCompletedProjects: "Abgeschlossene Projekte wählen",
  completeLabel: "Fertig",
  stageComplete: "Phase abgeschlossen",
  expeditionControl: "Expedition-Kontrolle",
  selectActiveExpedition: "Aktive Expedition wählen",
  authCodePlaceholder: "LOGIN-CODE EINGEBEN",
  authCodeValid: "Login-Code 5 Minuten gültig",
  syncUplink: "Registrieren",
  nameRequired: "Name erforderlich",
  authFailed: "Auth fehlgeschlagen",
  codeRequired: "Code erforderlich",
  codeExpired: "Code abgelaufen",
  codeInvalid: "Code ungültig",
  syncingUplink: "Verknüpfung wird geprüft...",
  noRaiderLinked: "Kein User angemeldet.",
  communityLabel: "Community",
  rosterTitle: "Mitglieder",
  noSignal: "Kein Signal.",
  establishUplink: "Erstelle eine Community, um zu starten.",
  joiningUplink: "Trete der Community bei...",
  communityNameLabel: "Community-Name",
  communityNamePlaceholder: "Community-Namen eingeben",
  createCommunity: "Community erstellen",
  needsVerb: "benötigt",
  membersLabel: "Mitglieder",
  severUplink: "User entfernen",
  inviteLinkTitle: "Einladungslink",
  inviteLinkAria: "Einladungslink",
  inviteHelp: "Link teilen, um weitere User hinzuzufügen.",
  confirmRemoval: "Entfernung bestätigen",
  actionLabel: "Aktion",
  removeRaiderPrompt: "User aus der Community entfernen?",
  cancel: "Abbrechen",
  confirm: "Bestätigen",
  severing: "Entferne...",
  raiders: "User",
  closeOverlay: "Overlay schließen",
  close: "Schließen",
  unknownLabel: "Unbekannt",
  increase: "Erhöhen",
  decrease: "Verringern",
  of: "von",
  noSignalTitle: "Kein Signal",
  idLabel: "ID",
};

export type LabelKey = keyof Labels;

export const getLabels = (locale: AppLocale): Labels => ({
  ...en,
  ...(locale === "de" ? de : {}),
});
