import type { AppLocale } from "@/lib/locale";

const en = {
  navHome: "Home",
  navBlueprints: "Blueprints",
  navHideout: "Hideout",
  navProjects: "Projects",
  navCommunity: "Community",
  navOperator: "User",
  mainNavigation: "Navigation",
  navBlueprintsSubtitle: "Track blueprint item progress.",
  navHideoutSubtitle: "Track all hideout workbench progress.",
  navProjectsSubtitle: "Track project progress and needs.",
  navCommunitySubtitle: "Which items does my community need?",
  navOperatorSubtitle: "Configuration, expeditions, device management",
  projectSelection: "Project selection",
  scanning: "Scanning...",
  scanningProjectCache: "Scanning project cache...",
  scanningExpeditionIndex: "Scanning expedition index...",
  activeProject: "Active",
  noActiveProjects: "No active projects found.",
  archived: "Finished",
  noProjectsCompleted: "No projects completed.",
  back: "Back",
  quicksearch: "Quicksearch",
  searchPlaceholder: "SEARCH...",
  filterNeededOnly: "Show needed items only",
  neededOnly: "Needed only",
  noProjectData: "Project data could not be loaded.",
  show: "Show",
  hide: "Hide",
  dataNotFoundScanning: "Data not found. Scanning...",
  dataNotFound: "No data found.",
  noExpeditionsFound: "No expedition data found.",
  notSignedIn: "You are not signed in.",
  raiderLabel: "User",
  authCodeLabel: "Login Code",
  authCodeValueAria: "Login code",
  authCodeHint: "Use this code on another device to sign in.",
  publicProfileLabel: "Public Profile",
  publicProfileLinkLabel: "Public Profile Link",
  publicProfileLinkAria: "Public profile link",
  publicProfileLinkHint: "Share this link so others can see your needed items.",
  publicProfileNotFound: "Public profile not found.",
  copy: "Copy",
  copied: "Copied",
  edit: "Edit",
  activeExpeditionLabel: "Active Expedition",
  noExpedition: "NO EXPEDITION",
  unknownExpedition: "UNKNOWN EXPEDITION",
  expeditionReady: "READY",
  expeditionResetNoticeTitle: "Expedition departure is active",
  expeditionResetNoticeBody:
    "Did you participate in the expedition? Confirm your reset flow to archive this cycle.",
  expeditionResetLabel: "Expedition reset",
  expeditionResetCta: "Run expedition reset",
  expeditionResetDialogLabel: "Expedition Reset",
  expeditionResetDialogTitle: "Confirm reset flow",
  expeditionResetExplainLine1:
    "Expeditions send your Raider beyond the Rust Belt and start a new cycle.",
  expeditionResetExplainLine2:
    "After departure, your next Raider keeps a unique edge until the next expedition leaves.",
  expeditionResetExplainLine3:
    "Use this when you have participated and want your account state aligned.",
  expeditionResetScopeLine:
    "This resets workshop and blueprints for your user only. Project entries stay untouched.",
  expeditionResetConfirm: "I participated",
  expeditionResetNextQuestion: "Start your next expedition now?",
  expeditionResetNextNo: "No, reset only",
  expeditionResetNextYes: "Yes, start next",
  updateFailed: "Update failed",
  logOut: "Log Out",
  authRegister: "Register",
  authUseCode: "Use Code",
  onboardingAccountPrompt: "Do you already have an account?",
  onboardingAccountHelp: "Choose how to link your user.",
  onboardingExistingHelp:
    "Generate an auth code on your existing device (User menu) and enter it below.",
  onboardingNewIntroTitle: "Welcome to Raiders Outpost",
  onboardingNewIntroBody:
    "Track what you need in Arc Raiders for blueprints, hideout workbenches, projects, and expeditions.",
  onboardingBlueprintsTitle: "Blueprints",
  onboardingBlueprintsBody:
    "Mark blueprint stages as completed if you already finished them.",
  onboardingHideoutTitle: "Hideout",
  onboardingHideoutBody:
    "Mark hideout workbench stages as completed when done.",
  onboardingCategoryProjectsTitle: "Projects",
  onboardingCategoryProjectsBody:
    "Enable projects you want to track. You can disable them any time.",
  onboardingExpeditionsTitle: "Expeditions",
  onboardingExpeditionsBody:
    "Mark expeditions you have already completed. We will pick your next available expedition automatically.",
  onboardingCompletedExpeditionsLabel: "Completed expeditions",
  onboardingAvailableExpeditionLabel: "Available expedition",
  onboardingTrackAvailableExpedition: "Track available expedition",
  onboardingNoAvailableExpedition: "All expeditions completed",
  onboardingNoExpeditions: "No expeditions",
  onboardingPhasesCompletedLabel: "Phases completed",
  onboardingBack: "Back",
  onboardingNext: "Next",
  raiderNameLabel: "User Name",
  callsignPlaceholder: "Enter user name",
  completeLabel: "Complete",
  projectActivation: "Project Activation",
  activeLabel: "Active",
  inactiveLabel: "Inactive",
  selectActiveExpedition: "Select active expedition",
  authCodePlaceholder: "ENTER LOGIN CODE",
  authCodeValid: "Login code valid for 5 minutes",
  syncUplink: "Register",
  nameRequired: "Name required",
  authFailed: "Auth failed",
  codeRequired: "Code required",
  codeExpired: "Code expired",
  codeInvalid: "Code invalid",
  syncingUplink: "Checking link...",
  noRaiderLinked: "No user signed in.",
  communityLabel: "Community",
  selectCommunities: "Communities",
  communityModeNeeds: "Community Needs",
  communityModeManage: "Community Manage",
  sortByLabel: "Sort",
  sortByMembers: "Members",
  sortByName: "Name",
  manageCommunities: "Manage communities",
  noCommunitiesSelected: "Select at least one community.",
  rosterTitle: "Members",
  establishUplink: "Create a community so everyone can track together they still need.",
  joiningUplink: "Joining community...",
  communityNameLabel: "Community Name",
  communityNamePlaceholder: "Enter community name",
  createCommunity: "Create community",
  createShort: "Create",
  communityInviteIntroTitle: "Communities coordinate shared item needs.",
  communityInviteIntroBody:
    "Invite users so everyone can track together what is still missing for projects.",
  needsVerb: "needs",
  membersLabel: "Members",
  inviteAction: "Invite",
  removeMember: "Remove",
  severUplink: "Remove",
  inviteLinkAria: "Invite link",
  inviteHelp: "Share the link to add more users.",
  confirmRemoval: "Confirm removal",
  actionLabel: "Action",
  removeRaiderPrompt: "Remove user from crew?",
  cancel: "Cancel",
  confirm: "Confirm",
  severing: "Removing...",
  raiders: "Users",
  closeOverlay: "Close overlay",
  close: "Close",
  unknownLabel: "Unknown",
  increase: "Increase",
  decrease: "Decrease",
  of: "of",
  notAvailable: "Unavailable",
} as const;

type Labels = Record<keyof typeof en, string>;

const de: Labels = {
  navHome: "Home",
  navBlueprints: "Blueprints",
  navHideout: "Werkstatt",
  navProjects: "Projekte",
  navCommunity: "Community",
  navOperator: "User",
  mainNavigation: "Navigation",
  navBlueprintsSubtitle: "Blueprint-Fortschritt verfolgen.",
  navHideoutSubtitle: "Fortschritt aller Werkbänke verfolgen.",
  navProjectsSubtitle: "Projektfortschritt und Bedarf verfolgen.",
  navCommunitySubtitle: "Welche Items braucht meine Community?",
  navOperatorSubtitle: "Konfiguration, Expedition, Geräteverwaltung",
  projectSelection: "Projektauswahl",
  scanning: "Scanne...",
  scanningProjectCache: "Scanne Projekt-Cache...",
  scanningExpeditionIndex: "Scanne Expeditionsindex...",
  activeProject: "Aktiv",
  noActiveProjects: "Keine aktiven Projekte gefunden.",
  archived: "Abgeschlossen",
  noProjectsCompleted: "Keine Projekte abgeschlossen.",
  back: "Zurück",
  quicksearch: "Schnellsuche",
  searchPlaceholder: "SUCHE...",
  filterNeededOnly: "Nur benötigte Items anzeigen",
  neededOnly: "Nur benötigt",
  noProjectData: "Projektdaten konnten nicht geladen werden.",
  show: "Anzeigen",
  hide: "Ausblenden",
  dataNotFoundScanning: "Daten nicht gefunden. Scanne...",
  dataNotFound: "Keine Daten gefunden.",
  noExpeditionsFound: "Keine Expeditionsdaten gefunden.",
  notSignedIn: "Du bist nicht angemeldet.",
  raiderLabel: "User",
  authCodeLabel: "Login-Code",
  authCodeValueAria: "Login-Code",
  authCodeHint: "Nutze diesen Code auf einem anderen Gerät, um dich anzumelden.",
  publicProfileLabel: "Öffentliches Profil",
  publicProfileLinkLabel: "Öffentlicher Profil-Link",
  publicProfileLinkAria: "Öffentlicher Profil-Link",
  publicProfileLinkHint:
    "Teile diesen Link, damit andere deine benötigten Items sehen können.",
  publicProfileNotFound: "Öffentliches Profil nicht gefunden.",
  copy: "Kopieren",
  copied: "Kopiert",
  edit: "Bearbeiten",
  activeExpeditionLabel: "Aktive Expedition",
  noExpedition: "KEINE EXPEDITION",
  unknownExpedition: "UNBEKANNTE EXPEDITION",
  expeditionReady: "BEREIT",
  expeditionResetNoticeTitle: "Expeditions-Abfahrt ist aktiv",
  expeditionResetNoticeBody:
    "Hast du an der Expedition teilgenommen? Bestätige den Reset-Ablauf, um diesen Zyklus abzuschließen.",
  expeditionResetLabel: "Expeditions-Reset",
  expeditionResetCta: "Expeditions-Reset ausführen",
  expeditionResetDialogLabel: "Expeditions-Reset",
  expeditionResetDialogTitle: "Reset-Ablauf bestätigen",
  expeditionResetExplainLine1:
    "Expeditionen schicken deinen Raider über den Rostgürtel hinaus und starten einen neuen Zyklus.",
  expeditionResetExplainLine2:
    "Nach der Abfahrt behält dein nächster Raider einen einzigartigen Vorteil bis zur nächsten Expedition.",
  expeditionResetExplainLine3:
    "Nutze das, wenn du teilgenommen hast und deinen Account-Status angleichen willst.",
  expeditionResetScopeLine:
    "Zurückgesetzt werden nur Workshop und Blueprints für deinen User. Projekt-Einträge bleiben unberührt.",
  expeditionResetConfirm: "Ich habe teilgenommen",
  expeditionResetNextQuestion: "Direkt die nächste Expedition starten?",
  expeditionResetNextNo: "Nein, nur reseten",
  expeditionResetNextYes: "Ja, nächste starten",
  updateFailed: "Update fehlgeschlagen",
  logOut: "Abmelden",
  authRegister: "Registrieren",
  authUseCode: "Code verwenden",
  onboardingAccountPrompt: "Hast du bereits einen Account?",
  onboardingAccountHelp: "Wähle den Weg zum Verknüpfen deines Users.",
  onboardingExistingHelp:
    "Erzeuge einen Auth-Code auf deinem bestehenden Gerät (User-Menü) und gib ihn unten ein.",
  onboardingNewIntroTitle: "Willkommen bei Raiders Outpost",
  onboardingNewIntroBody:
    "Verfolge, was du in Arc Raiders für Blueprints, Werkbänke, Projekte und Expeditionen brauchst.",
  onboardingBlueprintsTitle: "Blueprints",
  onboardingBlueprintsBody:
    "Markiere Blueprint-Stufen als abgeschlossen, wenn du sie bereits fertig hast.",
  onboardingHideoutTitle: "Werkstatt",
  onboardingHideoutBody:
    "Markiere Werkbank-Stufen als abgeschlossen, wenn erledigt.",
  onboardingCategoryProjectsTitle: "Projekte",
  onboardingCategoryProjectsBody:
    "Aktiviere Projekte, die du verfolgen willst. Du kannst sie jederzeit deaktivieren.",
  onboardingExpeditionsTitle: "Expeditionen",
  onboardingExpeditionsBody:
    "Markiere Expeditionen, die du bereits abgeschlossen hast. Wir wählen deine nächste verfügbare Expedition automatisch.",
  onboardingCompletedExpeditionsLabel: "Abgeschlossene Expeditionen",
  onboardingAvailableExpeditionLabel: "Verfügbare Expedition",
  onboardingTrackAvailableExpedition: "Verfügbare Expedition verfolgen",
  onboardingNoAvailableExpedition: "Alle Expeditionen abgeschlossen",
  onboardingNoExpeditions: "Keine Expeditionen",
  onboardingPhasesCompletedLabel: "Phasen abgeschlossen",
  onboardingBack: "Zurück",
  onboardingNext: "Weiter",
  raiderNameLabel: "User-Name",
  callsignPlaceholder: "User-Name eingeben",
  completeLabel: "Fertig",
  projectActivation: "Projektaktivierung",
  activeLabel: "Aktiv",
  inactiveLabel: "Inaktiv",
  selectActiveExpedition: "Aktive Expedition wählen",
  authCodePlaceholder: "LOGIN-CODE EINGEBEN",
  authCodeValid: "Login-Code 5 Minuten gültig",
  syncUplink: "Registrieren",
  nameRequired: "Name erforderlich",
  authFailed: "Auth fehlgeschlagen",
  codeRequired: "Code erforderlich",
  codeExpired: "Code abgelaufen",
  codeInvalid: "Code ungültig",
  syncingUplink: "Verknüpfung wird geprüft...",
  noRaiderLinked: "Kein User angemeldet.",
  communityLabel: "Community",
  selectCommunities: "Communities",
  communityModeNeeds: "Community-Bedarf",
  communityModeManage: "Community-Verwaltung",
  sortByLabel: "Sortierung",
  sortByMembers: "Mitglieder",
  sortByName: "Name",
  manageCommunities: "Communities verwalten",
  noCommunitiesSelected: "Wähle mindestens eine Community aus.",
  rosterTitle: "Mitglieder",
  establishUplink: "Erstelle eine Community, damit ihr zusammen verfolgen könnt, was euch noch fehlt",
  joiningUplink: "Trete der Community bei...",
  communityNameLabel: "Community-Name",
  communityNamePlaceholder: "Community-Namen eingeben",
  createCommunity: "Community erstellen",
  createShort: "Erstellen",
  communityInviteIntroTitle: "Communities koordinieren den gemeinsamen Item-Bedarf.",
  communityInviteIntroBody:
    "Lade User ein, damit ihr zusammen verfolgen könnt, was euch noch fehlt.",
  needsVerb: "benötigt",
  membersLabel: "Mitglieder",
  inviteAction: "Einladen",
  removeMember: "Entfernen",
  severUplink: "Entfernen",
  inviteLinkAria: "Einladungslink",
  inviteHelp: "Link teilen, um weitere User hinzuzufügen.",
  confirmRemoval: "Entfernung bestätigen",
  actionLabel: "Aktion",
  removeRaiderPrompt: "User aus der Community entfernen?",
  cancel: "Abbrechen",
  confirm: "Bestätigen",
  severing: "Entferne...",
  raiders: "User",
  closeOverlay: "Overlay schließen",
  close: "Schließen",
  unknownLabel: "Unbekannt",
  increase: "Erhöhen",
  decrease: "Verringern",
  of: "von",
  notAvailable: "Nicht verfügbar",
};

export type LabelKey = keyof Labels;

export const getLabels = (locale: AppLocale): Labels => ({
  ...en,
  ...(locale === "de" ? de : {}),
});
